### PR TITLE
added explanation for short circuit nature of && and || logical opera…

### PR DESCRIPTION
**Pull request by afreen23**

### CODE REVIEW

**Comment by pixari** [comment]
Well done! 
I've resolved the conflicts and merged the changes.

**Comment by pixari** [comment]
I'm also adding you to the contributor list: 

- https://github.com/pixari/dmfojs#contributors

**Comment by pixari** [comment]
@all-contributors please add @afreen23 for doc

**Comment by afreen23** [comment]
> Well done!
> I've resolved the conflicts and merged the changes.

thanx :+1: :)

**Pull request merged**
